# Generated by Django 5.0.4 on 2024-10-14 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='course',
        ),
        migrations.RemoveField(
            model_name='project',
            name='course',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enrollment',
            name='object_id',
            field=models.PositiveIntegerField(default=120),
            preserve_default=False,
        ),
    ]
